/**
 * Generate all app icons from the S monogram design:
 * 1. Tray icon template (black on transparent, 44x44 @2x) from SVG
 * 2. Recording tray icon (same + red dot)
 * 3. Base64 fallbacks in tray-icons.generated.ts
 * 4. Dock icon (warm copper S on dark bg, 1024x1024)
 * 5. In-app logo (128x128 from dock icon)
 *
 * Run: node scripts/generate-icons.mjs
 */
import sharp from 'sharp'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(__dirname, '..')
const TRAY_SIZE = 44 // 44px @2x = 22pt on Retina
const DOCK_SIZE = 1024
const COPPER = '#C8956C' // warm copper from the monogram design

// Compact S for menu bar — bolder stroke for visibility at 22pt
const TRAY_S_PATH = 'M 27 10 C 23 8, 17 9.5, 15.5 13 C 14 16.5, 16.5 19, 22 21 C 27.5 23, 30 25.5, 28.5 29.5 C 27 33.5, 22 35, 17 33'
const TRAY_S_STROKE = 4.5
// Pure black — macOS template images use alpha channel only; macOS applies the right color
const TRAY_TEMPLATE_COLOR = '#000000'

// Bolder S for dock/app icon (displayed at larger sizes)
const DOCK_S_PATH = 'M 29 6 C 23 4, 14 6, 12 12 C 10 18, 15 21, 22 23 C 29 25, 34 28, 32 34 C 30 40, 22 42, 15 39'
const DOCK_S_STROKE = 6

// ─── 1. Tray icon template from SVG ──────────────────────────────────────

async function generateTrayTemplate() {
  // Render the compact S monogram SVG — already black on transparent
  const svg = Buffer.from(`<svg width="${TRAY_SIZE}" height="${TRAY_SIZE}" viewBox="0 0 44 44" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="${TRAY_S_PATH}" stroke="${TRAY_TEMPLATE_COLOR}" stroke-width="${TRAY_S_STROKE}" stroke-linecap="round" fill="none"/>
  </svg>`)

  const templatePng = await sharp(svg)
    .resize(TRAY_SIZE, TRAY_SIZE, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer()

  return templatePng
}

// ─── 2. Recording icon: template + red dot ───────────────────────────────

async function generateRecordingIcon(templatePng) {
  const dotSize = Math.round(TRAY_SIZE * 0.28) // ~12px dot
  const dotX = TRAY_SIZE - dotSize - 1
  const dotY = 1
  const dotSvg = Buffer.from(`<svg width="${TRAY_SIZE}" height="${TRAY_SIZE}" xmlns="http://www.w3.org/2000/svg">
    <circle cx="${dotX + dotSize / 2}" cy="${dotY + dotSize / 2}" r="${dotSize / 2}" fill="#E53935"/>
  </svg>`)

  const recordingPng = await sharp(templatePng)
    .composite([{ input: dotSvg, top: 0, left: 0 }])
    .png()
    .toBuffer()

  return recordingPng
}

// ─── 3. Dock icon: copper S on dark rounded rect ─────────────────────────

async function generateDockIcon() {
  // Background
  const bgSvg = Buffer.from(`<svg width="${DOCK_SIZE}" height="${DOCK_SIZE}" xmlns="http://www.w3.org/2000/svg">
    <rect width="${DOCK_SIZE}" height="${DOCK_SIZE}" rx="${Math.round(DOCK_SIZE * 0.22)}" fill="#1C1C1E"/>
  </svg>`)

  // Bolder S in copper at dock resolution
  const sSvg = Buffer.from(`<svg width="${DOCK_SIZE}" height="${DOCK_SIZE}" viewBox="0 0 44 44" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="${DOCK_S_PATH}" stroke="${COPPER}" stroke-width="${DOCK_S_STROKE}" stroke-linecap="round" fill="none"/>
  </svg>`)

  const dockIcon = await sharp(bgSvg)
    .composite([{ input: await sharp(sSvg).png().toBuffer(), top: 0, left: 0 }])
    .png()
    .toBuffer()

  return dockIcon
}

// ─── 4. In-app logo from dock icon ───────────────────────────────────────

async function generateInAppLogo(dockPng) {
  const logoPng = await sharp(dockPng)
    .resize(128, 128, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer()
  return logoPng
}

// ─── Main ────────────────────────────────────────────────────────────────

async function main() {
  console.log('Generating icons from S monogram design...')

  // 1. Tray template
  const templatePng = await generateTrayTemplate()
  const trayDest = path.join(ROOT, 'electron', 'resources', 'tray-icon-template-2x.png')
  fs.writeFileSync(trayDest, templatePng)
  console.log(`  ✓ Tray template: ${trayDest} (${templatePng.length} bytes)`)

  const trayPublic = path.join(ROOT, 'public', 'tray-icon-template-2x.png')
  fs.writeFileSync(trayPublic, templatePng)
  console.log(`  ✓ Tray template (dev): ${trayPublic}`)

  // 2. Recording icon
  const recordingPng = await generateRecordingIcon(templatePng)
  console.log(`  ✓ Recording icon: ${recordingPng.length} bytes`)

  // 3. Base64 fallbacks
  const generatedTs = `// Generated by scripts/generate-icons.mjs — do not edit by hand
export const TRAY_ICON_BASE64 = '${templatePng.toString('base64')}'
export const TRAY_ICON_RECORDING_BASE64 = '${recordingPng.toString('base64')}'
`
  const generatedPath = path.join(ROOT, 'electron', 'main', 'tray-icons.generated.ts')
  fs.writeFileSync(generatedPath, generatedTs, 'utf8')
  console.log(`  ✓ Base64 fallbacks: ${generatedPath}`)

  // 4. Dock icon
  const dockPng = await generateDockIcon()
  const dockDest = path.join(ROOT, 'public', 'dock-icon-1024.png')
  fs.writeFileSync(dockDest, dockPng)
  console.log(`  ✓ Dock icon: ${dockDest} (${dockPng.length} bytes)`)

  // 5. In-app logo
  const logoPng = await generateInAppLogo(dockPng)
  const logoAsset = path.join(ROOT, 'src', 'assets', 'syag-logo-inapp.png')
  fs.writeFileSync(logoAsset, logoPng)
  console.log(`  ✓ In-app logo: ${logoAsset} (${logoPng.length} bytes)`)

  const logoPublic = path.join(ROOT, 'public', 'syag-logo-inapp.png')
  fs.writeFileSync(logoPublic, logoPng)
  console.log(`  ✓ In-app logo (public): ${logoPublic}`)

  console.log('\nDone! All icons generated from S monogram design.')
}

main().catch((err) => {
  console.error('Icon generation failed:', err)
  process.exit(1)
})
